# Название проекта

## Подготовка среды и библиотек

In [1]:
import pandas as pd

In [2]:
df_users = pd.read_csv('https://code.s3.yandex.net/datasets/ds_s13_users.csv')
df_visits = pd.read_csv('https://code.s3.yandex.net/datasets/ds_s13_visits.csv')
df_ads_activity = pd.read_csv('https://code.s3.yandex.net/datasets/ads_activity.csv')
df_surf_depth = pd.read_csv('https://code.s3.yandex.net/datasets/surf_depth.csv')
df_primary_device = pd.read_csv('https://code.s3.yandex.net/datasets/primary_device.csv')
df_cloud_usage = pd.read_csv('https://code.s3.yandex.net/datasets/cloud_usage.csv')

In [3]:
df_users.head()

                              user_id  age_category
0  f545-8c95aefe8d3e5548a689-a5b2fd39             4
1  cb48-5a0d6cde4d86ae10637e-c8ceb6ed             2
2  678b-614cd47d854b9d591db2-000b2e50             0
3  4ac0-dad169100b4a29b20818-b26ae7c5             4
4  f19b-9ac21ca973b41ecfa8c3-6a58191d             0

In [4]:
df_visits.head()

,date,daytime,session_id,user_id,website_category
0,2025-11-01,вечер,066e4e02-8c1f-45eb-a50f-178659abe698,0010-5cf8f6b38a7b6c70a021-009dbcda,Category 17
1,2025-11-01,вечер,0bce1749-3376-439c-9a22-f8ffbba00e9a,0010-5cf8f6b38a7b6c70a021-009dbcda,Category 19
2,2025-11-01,вечер,3445d8c4-221d-4d88-bb6a-a2939fe3c610,0010-5cf8f6b38a7b6c70a021-009dbcda,Category 18
3,2025-11-01,вечер,3bf97286-1d91-4aaa-af4a-ed58eceb8cd2,0010-5cf8f6b38a7b6c70a021-009dbcda,Category 20
4,2025-11-01,вечер,40e22712-3cad-410d-a9f0-13bd8f6911c0,0010-5cf8f6b38a7b6c70a021-009dbcda,Category 05

In [5]:
df_ads_activity.head()

                              user_id ads_activity
0  e318-d8e69c86b543a5fb927c-c36fb6e6  очень часто
1  35cd-a972339dec534f49332c-a8b6d383        редко
2  f7e6-3b29cf9cb7ed4bb00d8f-81534360  очень редко
3  5186-e25a37549e50f45b2b43-178eaabe     умеренно
4  febd-077f277466253ee04ef6-42656680     умеренно

In [6]:
df_surf_depth.head()

                              user_id    surf_depth
0  f238-0c4c1e787cce311541b7-736925a0  поверхностно
1  9030-1b562ad80182b6dc27f1-ce811740       глубоко
2  22e0-7c6cadcc45e246b8688d-c43c9b23  поверхностно
3  9d7f-a19f10756378940a49b5-5d03e1ef  поверхностно
4  4233-bb5ae4b09827e5497094-1a4956af       глубоко

In [7]:
df_primary_device.head()

                              user_id primary_device
0  d602-ec060db7597a6b8cd4e7-aa625896       смартфон
1  9204-9558455be649d4e77945-b5e25d62             ПК
2  5eea-22babd6a9474b43b9d0b-a39a4cf2        ноутбук
3  c142-0296948e8d08e417de10-2da9523c       смартфон
4  abec-bb4092da51eb2233a928-e44ba074             ПК

In [8]:
df_cloud_usage.head()

                              user_id  cloud_usage
0  a1e4-91c8a52eb855595e653f-298ce305        False
1  db9a-7b8e9e94448b7fcb19b6-4edca15f        False
2  0d55-9ad768879e9b08ca7ff9-843f76c7         True
3  4baa-43285d10a6d3cc969f2a-b21881d1        False
4  b8cd-cbb2411db005115ca64d-32700c62        False

## Исследовательский анализ данных

## Предобработка данных

## Обучение и оценка базовой модели

## Создание и отбор признаков

## Подбор гиперпараметров моделей

## Подготовка артефактов модели для внедрения

## Выводы о результатах работы